name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: FTP Deploy to gicpctalaga.page.gd
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            database/**
            user_guide/**
            user_guide_src/**
            vendor/**
            README.md
            readme.rst
            phpdoc.dist.xml
            composer.json
            composer.lock