name: 🚀 Deploy via FTP

on:
  push:
    branches:
      - main
      - staging

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Show Branch
        run: |
          echo "Branch: $GITHUB_REF"

      # LIVE SITE
      - name: FTP Deploy to Live
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_42125686
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: htdocs/
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            database/**
            user_guide/**
            user_guide_src/**
            vendor/**
            README.md
            readme.rst
            phpdoc.dist.xml
            composer.json
            composer.lock

      # STAGING SITE
      - name: FTP Deploy to Staging
        if: github.ref == 'refs/heads/staging'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_42125686
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: gicpcstaging/htdocs/
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            database/**
            user_guide/**
            user_guide_src/**
            vendor/**
            README.md
            readme.rst
            phpdoc.dist.xml
            composer.json
            composer.lock